@baseUrl = http://localhost:4004/sample
@dummyAuth = Basic ZHVtbXk6ZHVtbXk=

### GET todos os agendamentos
GET {{baseUrl}}/Appointments
Authorization: {{dummyAuth}}

### POST criar novo agendamento (verificar se o totalCost é calculado)
POST {{baseUrl}}/Appointments
Content-Type: application/json
Authorization: {{dummyAuth}}

{
  "date": "2026-04-15T14:30:00Z",
  "notes": "Rotina checkup",
  "pet_id": "fe51eaee-f4b0-4552-9091-059ad5b769b0",
  "veterinarian_id": "091bb664-e13c-457a-9b65-c633596b52f4",
  "procedures": [
    {
      "description": "Vaccination",
      "cost": 50.00
    },
    {
      "description": "Physical examination",
      "cost": 30.00
    }
  ]
}

### GET agendamento específico por ID
GET {{baseUrl}}/Appointments(a13a674a-abdd-4988-bbe6-bd37c5137361)
Authorization: {{dummyAuth}}

### GET com $filter por status
GET {{baseUrl}}/Appointments?$filter=status eq 'SCHEDULED'
Authorization: {{dummyAuth}}
