@baseUrl = http://localhost:4004/sample
@dummyAuth = Basic ZHVtbXk6ZHVtbXk=

### GET todos os owners
GET {{baseUrl}}/Owners
Authorization: {{dummyAuth}}

### POST criar novo owner
POST {{baseUrl}}/Owners
Content-Type: application/json
Authorization: {{dummyAuth}}

{
  "firstName": "João",
  "lastName": "Silva",
  "phone": "11987654321",
  "email": "joao.silva@email.com"
}

### GET owner específico por ID
GET {{baseUrl}}/Owners(81ffd7bc-8523-4d8e-8e27-db44959b2bea)
Authorization: {{dummyAuth}}

### GET com $expand para trazer os pets do owner
GET {{baseUrl}}/Owners?$expand=pets
Authorization: {{dummyAuth}}
