@baseUrl = http://localhost:4004/sample
@dummyAuth = Basic ZHVtbXk6ZHVtbXk=

### GET todos os veterinários
GET {{baseUrl}}/Veterinarians
Authorization: {{dummyAuth}}

### POST criar novo veterinário
POST {{baseUrl}}/Veterinarians
Content-Type: application/json
Authorization: {{dummyAuth}}

{
  "firstName": "Maria",
  "lastName": "Santos",
  "specialty": "Dentistry",
  "crmv": "CRMV99999"
}