@baseUrl = http://localhost:4004/sample

GET {{baseUrl}}/getVeterinarianSchedule(veterinarianId='11111111-1111-1111-1111-111111111111', days=30)
Authorization: Basic dummy:dummy
Content-Type: application/json
