name: Gitflow CI

on:
  pull_request_review:
    types: [submitted]
    branches: [main, quality]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    name: Gitflow CI
    steps:
      - uses: actions/checkout@v2
      - name: Run gitflow process
        uses: VAEES/git-flow-action@main
        with:
          github_token: ${{ secrets.ADMIN_TOKEN }}
          master_branch: 'main'
          development_branch: 'quality'